In [43]:
import numpy as np 
import pandas as pd 

In [44]:
df=pd.read_csv('Clean_travel.csv')

In [45]:
df.head()

Unnamed: 0  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0           0          1  41.0     Self Enquiry         3              6.0   
1           1          0  49.0  Company Invited         1             14.0   
2           2          1  37.0     Self Enquiry         1              8.0   
3           3          0  33.0  Company Invited         1              9.0   
4           4          0  36.0     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfFollowups ProductPitched  \
0        Salaried  Female                3.0         Deluxe   
1        Salaried    Male                4.0         Deluxe   
2     Free Lancer    Male                4.0          Basic   
3        Salaried  Female                3.0          Basic   
4  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0     Unmarried            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0     Unmarried            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  TotalVisiting  
0                       2       1     Manager        20993.0            3.0  
1                       3       1     Manager        20130.0            5.0  
2                       3       0   Executive        17090.0            3.0  
3                       5       1   Executive        17909.0            3.0  
4                       5       1   Executive        18468.0            2.0

In [46]:
x=df.drop('ProdTaken',axis=1)
x

Unnamed: 0   Age    TypeofContact  CityTier  DurationOfPitch  \
0              0  41.0     Self Enquiry         3              6.0   
1              1  49.0  Company Invited         1             14.0   
2              2  37.0     Self Enquiry         1              8.0   
3              3  33.0  Company Invited         1              9.0   
4              4  36.0     Self Enquiry         1              8.0   
...          ...   ...              ...       ...              ...   
4883        4883  49.0     Self Enquiry         3              9.0   
4884        4884  28.0  Company Invited         1             31.0   
4885        4885  52.0     Self Enquiry         3             17.0   
4886        4886  19.0     Self Enquiry         3             16.0   
4887        4887  36.0     Self Enquiry         1             14.0   

          Occupation  Gender  NumberOfFollowups ProductPitched  \
0           Salaried  Female                3.0         Deluxe   
1           Salaried    Male                4.0         Deluxe   
2        Free Lancer    Male                4.0          Basic   
3           Salaried  Female                3.0          Basic   
4     Small Business    Male                3.0          Basic   
...              ...     ...                ...            ...   
4883  Small Business    Male                5.0         Deluxe   
4884        Salaried    Male                5.0          Basic   
4885        Salaried  Female                4.0       Standard   
4886  Small Business    Male                4.0          Basic   
4887        Salaried    Male                4.0          Basic   

      PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                       3.0     Unmarried            1.0         1   
1                       4.0      Divorced            2.0         0   
2                       3.0     Unmarried            7.0         1   
3                       3.0      Divorced            2.0         1   
4                       4.0      Divorced            1.0         0   
...                     ...           ...            ...       ...   
4883                    4.0     Unmarried            2.0         1   
4884                    3.0     Unmarried            3.0         1   
4885                    4.0       Married            7.0         0   
4886                    3.0     Unmarried            3.0         0   
4887                    4.0     Unmarried            3.0         1   

      PitchSatisfactionScore  OwnCar     Designation  MonthlyIncome  \
0                          2       1         Manager        20993.0   
1                          3       1         Manager        20130.0   
2                          3       0       Executive        17090.0   
3                          5       1       Executive        17909.0   
4                          5       1       Executive        18468.0   
...                      ...     ...             ...            ...   
4883                       1       1         Manager        26576.0   
4884                       3       1       Executive        21212.0   
4885                       1       1  Senior Manager        31820.0   
4886                       5       0       Executive        20289.0   
4887                       3       1       Executive        24041.0   

      TotalVisiting  
0               3.0  
1               5.0  
2               3.0  
3               3.0  
4               2.0  
...             ...  
4883            4.0  
4884            6.0  
4885            7.0  
4886            5.0  
4887            6.0  

[4888 rows x 18 columns]

In [47]:
y=df['ProdTaken']

## Train Test Split

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

## ONE HOT ENCODING

In [49]:
cat_features = x.select_dtypes(include="object").columns
num_features = x.select_dtypes(exclude="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
         ("OneHotEncoder", oh_transformer, cat_features),
          ("StandardScaler", numeric_transformer, num_features)
    ]
)

preprocessor


x_train=preprocessor.fit_transform(x_train)


pd.DataFrame(x_train)

x_test=preprocessor.transform(x_test)

## Model Training & Testing

In [50]:
from sklearn.ensemble import AdaBoostClassifier

classifier=AdaBoostClassifier()

classifier.fit(x_train,y_train)

c:\Users\Syed Ali Zar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier()

In [51]:
x_train_pred=classifier.predict(x_train)

In [52]:
y_pred=classifier.predict(x_test)

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
matrix=confusion_matrix(y_train,x_train_pred)
report=classification_report(y_train,x_train_pred)
acc=accuracy_score(y_train,x_train_pred)

print('For Training Set')
print("Accuracy Score: ",acc)
print('Confusion Matrix:')
print(matrix)
print("Classification Report: ")
print(report)

print("-----------------------------")
print("For Test Set")
matrix=confusion_matrix(y_test,y_pred)
report=classification_report(y_test,y_pred)
acc=accuracy_score(y_test,y_pred)

print("Accuracy Score: ",acc)
print('Confusion Matrix:')
print(matrix)
print("Classification Report: ")
print(report)

For Training Set
Accuracy Score:  0.8713826366559485
Confusion Matrix:
[[2706   69]
 [ 371  275]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.88      0.98      0.92      2775
           1       0.80      0.43      0.56       646

    accuracy                           0.87      3421
   macro avg       0.84      0.70      0.74      3421
weighted avg       0.86      0.87      0.86      3421

-----------------------------
For Test Set
Accuracy Score:  0.8513974096796183
Confusion Matrix:
[[1146   47]
 [ 171  103]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1193
           1       0.69      0.38      0.49       274

    accuracy                           0.85      1467
   macro avg       0.78      0.67      0.70      1467
weighted avg       0.84      0.85      0.83      1467



### HyperParameter Tuning

In [54]:
from sklearn.model_selection import GridSearchCV

In [55]:
params={
    'n_estimators':[50,60,70,80,90],
    'algorithm':['SAMME','SAMME.R']
}

params

{'n_estimators': [50, 60, 70, 80, 90], 'algorithm': ['SAMME', 'SAMME.R']}

In [56]:
grid=GridSearchCV(estimator=classifier,param_grid=params,cv=3,verbose=2,n_jobs=-1)

In [57]:
grid.fit(x_train,y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


c:\Users\Syed Ali Zar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


GridSearchCV(cv=3, estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['SAMME', 'SAMME.R'],
                         'n_estimators': [50, 60, 70, 80, 90]},
             verbose=2)

In [58]:
grid.best_params_

{'algorithm': 'SAMME.R', 'n_estimators': 90}

In [59]:
grid.best_index_

9

In [60]:
grid.best_score_

0.8617387025846827

In [61]:
y_pred=grid.predict(x_test)

In [62]:
x_train_pred=grid.predict(x_train)

In [63]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
matrix=confusion_matrix(y_train,x_train_pred)
report=classification_report(y_train,x_train_pred)
acc=accuracy_score(y_train,x_train_pred)

print('For Training Set For HyperParameter Tuning')
print("Accuracy Score: ",acc)
print('Confusion Matrix:')
print(matrix)
print("Classification Report: ")
print(report)

print("-------------------------------------------")
print("For Testing Set For HyperParameter Tuning")
matrix=confusion_matrix(y_test,y_pred)
report=classification_report(y_test,y_pred)
acc=accuracy_score(y_test,y_pred)

print("Accuracy Score: ",acc)
print('Confusion Matrix:')
print(matrix)
print("Classification Report: ")
print(report)

For Training Set For HyperParameter Tuning
Accuracy Score:  0.8783981292019877
Confusion Matrix:
[[2707   68]
 [ 348  298]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.89      0.98      0.93      2775
           1       0.81      0.46      0.59       646

    accuracy                           0.88      3421
   macro avg       0.85      0.72      0.76      3421
weighted avg       0.87      0.88      0.86      3421

-------------------------------------------
For Testing Set For HyperParameter Tuning
Accuracy Score:  0.8541240627130198
Confusion Matrix:
[[1148   45]
 [ 169  105]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.87      0.96      0.91      1193
           1       0.70      0.38      0.50       274

    accuracy                           0.85      1467
   macro avg       0.79      0.67      0.71      1467
weighted avg       0.84      0.85      0.84      1467

