Import Libraries

In [19]:
import numpy as np
import pandas as pd

Load DataSet

In [20]:
df=pd.read_csv('drug200.csv')
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

Declare X & Y

In [21]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
x,y

(array([[23, 'F', 'HIGH', 'HIGH', 25.355],
        [47, 'M', 'LOW', 'HIGH', 13.093],
        [47, 'M', 'LOW', 'HIGH', 10.114],
        [28, 'F', 'NORMAL', 'HIGH', 7.798],
        [61, 'F', 'LOW', 'HIGH', 18.043],
        [22, 'F', 'NORMAL', 'HIGH', 8.607],
        [49, 'F', 'NORMAL', 'HIGH', 16.275],
        [41, 'M', 'LOW', 'HIGH', 11.037],
        [60, 'M', 'NORMAL', 'HIGH', 15.171],
        [43, 'M', 'LOW', 'NORMAL', 19.368],
        [47, 'F', 'LOW', 'HIGH', 11.767],
        [34, 'F', 'HIGH', 'NORMAL', 19.199],
        [43, 'M', 'LOW', 'HIGH', 15.376],
        [74, 'F', 'LOW', 'HIGH', 20.942],
        [50, 'F', 'NORMAL', 'HIGH', 12.703],
        [16, 'F', 'HIGH', 'NORMAL', 15.516],
        [69, 'M', 'LOW', 'NORMAL', 11.455],
        [43, 'M', 'HIGH', 'HIGH', 13.972],
        [23, 'M', 'LOW', 'HIGH', 7.298],
        [32, 'F', 'HIGH', 'NORMAL', 25.974],
        [57, 'M', 'LOW', 'NORMAL', 19.128],
        [63, 'M', 'NORMAL', 'HIGH', 25.917],
        [47, 'M', 'LOW', 'NORMAL', 30.568],


Filling Missing Values

In [22]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'most_frequent')

imputer = imputer.fit(x[:,0:4])
x[:,0:4]= imputer.transform(x[:, 0:4])

Label Encoding

In [23]:
from sklearn.preprocessing import LabelEncoder
labelEncoder_X = LabelEncoder()
#CHANGE THE INDEX FOR APPROPRIATE COLUMNS OF X
x[:,1] = labelEncoder_X.fit_transform(x[:,1])
x[:,2] = labelEncoder_X.fit_transform(x[:,2])
x[:,3] = labelEncoder_X.fit_transform(x[:,3])

labelEncoder_y = LabelEncoder()
y = labelEncoder_y.fit_transform(y)
y

array([4, 2, 2, 3, 4, 3, 4, 2, 4, 4, 2, 4, 4, 4, 3, 4, 3, 0, 2, 4, 4, 4,
       4, 4, 4, 4, 4, 3, 4, 4, 3, 1, 3, 4, 3, 3, 0, 3, 3, 3, 4, 1, 4, 3,
       3, 3, 0, 2, 4, 4, 4, 3, 4, 4, 1, 2, 1, 4, 3, 4, 4, 0, 4, 3, 1, 4,
       0, 3, 4, 4, 1, 4, 3, 4, 4, 4, 0, 4, 0, 3, 1, 3, 2, 0, 2, 1, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 0, 0, 2, 3, 4, 3, 3, 4, 1, 4,
       0, 3, 3, 3, 3, 4, 3, 3, 0, 4, 4, 4, 4, 4, 1, 4, 4, 3, 4, 3, 4, 4,
       3, 4, 4, 3, 1, 0, 1, 3, 0, 4, 1, 4, 0, 3, 3, 0, 3, 2, 0, 1, 3, 3,
       4, 2, 0, 4, 2, 3, 3, 1, 3, 4, 4, 4, 4, 3, 4, 0, 3, 3, 4, 4, 0, 4,
       0, 4, 4, 4, 4, 3, 3, 4, 4, 4, 1, 0, 4, 4, 4, 0, 4, 2, 4, 2, 2, 3,
       3, 3])

X Inputs After Label Encoding

In [24]:
x

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043],
       [22, 0, 2, 0, 8.607],
       [49, 0, 2, 0, 16.275],
       [41, 1, 1, 0, 11.037],
       [60, 1, 2, 0, 15.171],
       [43, 1, 1, 1, 19.368],
       [47, 0, 1, 0, 11.767],
       [34, 0, 0, 1, 19.199],
       [43, 1, 1, 0, 15.376],
       [74, 0, 1, 0, 20.942],
       [50, 0, 2, 0, 12.703],
       [16, 0, 0, 1, 15.516],
       [69, 1, 1, 1, 11.455],
       [43, 1, 0, 0, 13.972],
       [23, 1, 1, 0, 7.298],
       [32, 0, 0, 1, 25.974],
       [57, 1, 1, 1, 19.128],
       [63, 1, 2, 0, 25.917],
       [47, 1, 1, 1, 30.568],
       [48, 0, 1, 0, 15.036],
       [33, 0, 1, 0, 33.486],
       [28, 0, 0, 1, 18.809],
       [31, 1, 0, 0, 30.366],
       [49, 0, 2, 1, 9.381],
       [39, 0, 1, 1, 22.697],
       [45, 1, 1, 0, 17.951],
       [18, 0, 2, 1, 8.75],
       [74, 1, 0, 0, 9.567],
       [49, 1, 1, 1, 11.014],
       [65, 0, 0,

Train Test Split

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

Apply Decision Tree Classifier

In [26]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train, y_train)


DecisionTreeClassifier(random_state=42)

Y-Pred for DT

In [27]:
y_pred_dt = decision_tree.predict(x_test)
y_pred_dt

array([2, 3, 4, 4, 4, 3, 3, 3, 4, 3, 0, 4, 4, 4, 1, 2, 4, 4, 3, 4, 4, 3,
       3, 3, 4, 4, 4, 4, 4, 3, 3, 2, 0, 3, 4, 4, 3, 4, 0, 3, 4, 0, 4, 3,
       4, 3, 4, 4, 0, 4, 4, 1, 4, 4, 2, 4, 3, 3, 4, 1])

Evaluation (Accuracy Score, Classification Report , Confusion Matrix)

In [28]:
from sklearn.metrics import accuracy_score, classification_report,  confusion_matrix
accuracy_dt = accuracy_score(y_test, y_pred_dt)
report_dt = classification_report(y_test, y_pred_dt)
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

Confusion Matrix:
[[ 5  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 18  0]
 [ 0  0  0  0 30]]


Print Accuracy & Classification Report

In [29]:
print("Decision Tree Classifier:")
print("Accuracy:", accuracy_dt)
print("Classification Report:")
print(report_dt)

Decision Tree Classifier:
Accuracy: 1.0
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00        18
           4       1.00      1.00      1.00        30

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60



HyperParameter Tuning

In [30]:
print("GG0",format(decision_tree.score(x_train,y_train)))
print("FF",format(decision_tree.score(x_test,y_test)))

GG0 1.0
FF 1.0


In [31]:
from sklearn.model_selection import GridSearchCV
dt = {
    'max_depth': [3, 5, 7, 10, None]
}
grid_dt = GridSearchCV(DecisionTreeClassifier(random_state=42), dt, cv=5)
grid_dt.fit(x_train, y_train)

print("Best parameters for Decision Tree:", grid_dt.best_params_)

Best parameters for Decision Tree: {'max_depth': 5}


Apply Random Forest Classifier

In [32]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(random_state=42)
random_forest.fit(x_train, y_train)


RandomForestClassifier(random_state=42)

Y-Predist for RF

In [33]:
y_pred_rf = random_forest.predict(x_test)
y_pred_rf

array([2, 3, 4, 4, 4, 3, 3, 3, 4, 3, 0, 4, 4, 4, 1, 2, 4, 4, 3, 4, 4, 3,
       3, 3, 4, 4, 4, 4, 4, 3, 3, 2, 0, 3, 4, 4, 3, 4, 0, 3, 4, 0, 4, 3,
       4, 3, 4, 4, 0, 4, 4, 1, 4, 4, 2, 4, 3, 3, 4, 1])

Evaluation (Accurcy, Classification Report, Confusion Matrix)

In [34]:
accuracy_rf = accuracy_score(y_test, y_pred_rf)
report_rf = classification_report(y_test, y_pred_rf)
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

Confusion Matrix:
[[ 5  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 18  0]
 [ 0  0  0  0 30]]


Print Accuracy & Classification Report for RF

In [35]:
print("Random Forest Classifier:")
print("Accuracy:", accuracy_rf)
print("Classification Report For Random Forest:")
print(report_rf)

Random Forest Classifier:
Accuracy: 1.0
Classification Report For Random Forest:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00        18
           4       1.00      1.00      1.00        30

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60



HyperParameter Tuning for RF

In [36]:
rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7, 10, None]
}
grid_rf = GridSearchCV(RandomForestClassifier(random_state=42), rf, cv=5)
grid_rf.fit(x_train, y_train)

print("Best parameters for Random Forest:", grid_rf.best_params_)

Best parameters for Random Forest: {'max_depth': 5, 'n_estimators': 100}
